<?xml version="1.0" encoding="UTF-8"?>
<museScore version="4.00">
  <Style>
    <pageWidth>8.5</pageWidth>
    <pageHeight>11</pageHeight>
    <pagePrintableWidth>7.5</pagePrintableWidth>
    <pageEvenLeftMargin>0.5</pageEvenLeftMargin>
    <pageOddLeftMargin>0.5</pageOddLeftMargin>
    <pageEvenTopMargin>0.25</pageEvenTopMargin>
    <pageOddTopMargin>0.25</pageOddTopMargin>
    <pageEvenBottomMargin>0.25</pageEvenBottomMargin>
    <pageOddBottomMargin>0.25</pageOddBottomMargin>
    <Spatium>1.5</Spatium>
    <staffUpperBorder>0.8</staffUpperBorder>
    <staffLowerBorder>0.8</staffLowerBorder>
    <minSystemDistance>3</minSystemDistance>
    <maxSystemDistance>7</maxSystemDistance>
    <enableVerticalSpread>0</enableVerticalSpread>
    <lyricsMinDistance>1</lyricsMinDistance>
    <lyricsMinBottomDistance>0.5</lyricsMinBottomDistance>
    <harmonyFretDist>1.2</harmonyFretDist>
    <minHarmonyDistance>0.5</minHarmonyDistance>
    <hideEmptyStaves>1</hideEmptyStaves>
    <dontHideStavesInFirstSystem>0</dontHideStavesInFirstSystem>
    <genCourtesyTimesig>0</genCourtesyTimesig>
    <genCourtesyClef>0</genCourtesyClef>
    <showHeader>1</showHeader>
    <headerFirstPage>0</headerFirstPage>
    <headerOddEven>0</headerOddEven>
    <evenHeaderL></evenHeaderL>
    <evenHeaderC></evenHeaderC>
    <evenHeaderR>$p</evenHeaderR>
    <oddHeaderL></oddHeaderL>
    <oddHeaderC></oddHeaderC>
    <oddHeaderR>$p</oddHeaderR>
    <showFooter>1</showFooter>
    <footerFirstPage>1</footerFirstPage>
    <footerOddEven>0</footerOddEven>
    <evenFooterL></evenFooterL>
    <evenFooterC>$:copyright:</evenFooterC>
    <evenFooterR></evenFooterR>
    <oddFooterL></oddFooterL>
    <oddFooterC>$:copyright:</oddFooterC>
    <oddFooterR></oddFooterR>
    <footerFontSize>5</footerFontSize>
  </Style>
</museScore>
